config/routes.rb
Rails.application.routes.draw do

  root 'shoes#index' # shortcut for the above
  
  # Routes for RestAPI
  namespace :api do
    resources :shoes, except: [:new, :edit], defaults: { format: :json }
  end

  resources :shoes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :shoes
end

app/models/shoe.rb
class Shoe < ApplicationRecord
	has_attached_file :picture, styles: { medium: '300x300>', thumb: '100x100>' },
		default_url: '/images/:style/missing.png'

	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

	belongs_to :brand

  def self.search(search)
    if search
      where('model LIKE ?', "%#{search}%")
      # find(:all, :conditions => ['model LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/api/application_controller.rb
module Api 
  class ApplicationController < ActionController::API
    rescue_from ActiveRecord::RecordNotFound,
    with: :respond_with_not_found
    
    private
    
    def render_error(status, resource = nil)
      render status: status,
      json: (resource ? { error: resource } : nil)
    end
    
    def respond_with_not_found(exception)
      render_error :not_found,
      {
        status: 404,
        name: "Not found",
        message: exception.message
      }
    end
  end
end

app/controllers/api/shoes_controller.rb
class Api::ShoesController < ApplicationController
  #La siguiente linea es para saltar autenticación, y realizar pruebas por postman.
  skip_before_action :verify_authenticity_token, :only => [:create, :updte, :destroy]

	before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  def index
  	@shoes = Shoe.all
  end

  def show
  end

  def create
    @shoe = Shoe.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.json { render :show, status: :created, location: @shoe }
      else
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  def update
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.json { render :show, status: :ok, location: @shoe }
      else
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  def destroy
    @shoe.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_shoe
    @shoe = Shoe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def shoe_params
    params.require(:shoe).permit(
    	:model,
    	:isbn,
    	:release_year,
    	:sku,
    	:picture,
    	:brand_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  # GET /shoes
  # GET /shoes.json
  def index
    # @shoes = Shoe.all
    @shoes = Shoe.search(params[:search])

  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
  end

  # GET /shoes/new
  def new
    @shoe = Shoe.new
  end

  # GET /shoes/1/edit
  def edit
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = Shoe.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render :show, status: :created, location: @shoe }
      else
        format.html { render :new }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { render :show, status: :ok, location: @shoe }
      else
        format.html { render :edit }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe.destroy
    respond_to do |format|
      format.html { redirect_to shoes_url, notice: 'Shoe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
      params.require(:shoe).permit(:model, :isbn, :release_year, :sku, :picture, :brand_id)
    end
end

app/helpers/api/shoes_helper.rb
module Api::ShoesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def attribute_shoe(letter, attribute, value, color = 'purple')
    content_tag(:span, class: 'mdl-chip mdl-chip--contact') do
      content_tag(:span, letter, class: "mdl-chip__contact mdl-color--#{color} mdl-color-text--white") +
      content_tag(:span,  class: 'mdl-chip__text') do
        content_tag(:strong, attribute.to_s.capitalize + ': ' ) + value.to_s
      end
    end
  end
end

app/helpers/my_mdl_form_builder.rb
class MyMdlFormBuilder < ActionView::Helpers::FormBuilder

  def select_belongs_to(model, belongs_to_model, option_field)
    belongs_to_model = belongs_to_model.to_s
    field_wrapper do 
      @template.content_tag(:p, belongs_to_model.capitalize, for: "#{@object_name}_#{belongs_to_model}_id", class: "mdl-select__label") +
      @template.collection_select(model, "#{belongs_to_model}_id", belongs_to_model.classify.constantize.all, :id, option_field, {prompt: false})      
    end
  rescue
    nil
  end

  def text_field(attribute, args)
    generic_field(attribute, args) do |attibute, args|
      super(attibute, args)
    end
  end

  def number_field(attribute, args)
    generic_field(attribute, args) do |attibute, args|
      super(attibute, args)
    end
  end
  
  def file_field(attribute, args)
    @template.content_tag(:div, { class: 'mdl-textfield mdl-js-textfield mdl-textfield--file' }) do
      @template.text_field_tag(:file, nil, {class: 'mdl-textfield__input', id: 'uploadFile', placeholder: 'Photo', readonly: true}) +
      @template.content_tag(:div, class: 'mdl-button mdl-button--primary mdl-button--icon mdl-button--file') do
        @template.content_tag(:i, 'attach_file',class: 'material-icons') + super(attribute,args.merge({id: 'uploadBtn'}))
      end
    end
  end
  
  private 
  def generic_field(attribute, args)
    field_wrapper do
      generic_label(attribute) +
      yield(attribute, args.merge({class: 'mdl-textfield__input'})) + span_error(attribute)
    end
  end

  def field_wrapper(&block)
    @template.content_tag(:div, { class: 'mdl-textfield mdl-js-textfield mdl-textfield--floating-label' }) do
      block.call
    end
  end
  
  def select_wrapper(&block)
    @template.content_tag(:div, { class: 'mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fullwidth' }) do
      block.call
    end
  end
  
  def file_field_wrapper
    @template.content_tag(:div, { class: 'mdl-textfield mdl-js-textfield mdl-textfield--file' }) do
      block.call
    end
  end
    
  def span_error(attribute)
    if @object.errors[attribute].present?
      @template.content_tag(:span, @object.errors[attribute.to_sym].join(", ").try(:capitalize), class: 'mdl-textfield__message-error ')      
    else
      ''
    end      
  end
    
  def generic_label(attribute)
    @template.content_tag(:label, attribute.capitalize, for: "#{@object_name}_#{attribute}", class: "mdl-textfield__label")    
  end
  
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoeStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <%= link_to 'Shoe Store', root_path, class: 'mdl-layout-title site-title' %>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation. We hide it in small screens. -->
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <%=link_to t(".shoes"), shoes_path, class: 'mdl-navigation__link' %>
          </nav>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Shoe Store</span>
        <nav class="mdl-navigation">
          <%=link_to t(".shoes"), shoes_path, class: 'mdl-navigation__link' %>
        </nav>
      </div>
      <main class="mdl-layout__content">
        <div class="page-content">
          <%= yield %>
        </div>
      </main>
      <footer class="mdl-mini-footer">
        <div class="mdl-mini-footer__left-section">
          <div class="mdl-logo">
            A subdivision of Rocketpin companies
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/shoes/_form.html.erb
<%= form_with(model: shoe, local: true) do |form| %>
  <% if shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% shoe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form.text_field :model, id: :shoe_model, class: 'mdl-textfield__input' %>
    <%= form.label :model, class: 'mdl-textfield__label' %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.collection_select(:brand_id, Brand.all, :id, :name) %>
  </div>

  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form.text_field :isbn, id: :shoe_isbn, class: 'mdl-textfield__input' %>
    <%= form.label :isbn, class: 'mdl-textfield__label' %>
  </div>
  <br>

  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form.number_field :release_year, id: :shoe_release_year, class: 'mdl-textfield__input' %>
    <%= form.label :release_year, class: 'mdl-textfield__label' %>
  </div>
  <br>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form.number_field :sku, id: :shoe_sku, class: 'mdl-textfield__input' %>
    <%= form.label :sku, class: 'mdl-textfield__label' %>
  </div>

  <div class="field">
    <%= form.file_field :picture %>
  </div>

  <%= form.submit 'Enviar', class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored', style: 'margin-top: 10px;' %>
<% end %>

app/views/shoes/edit.html.erb
<%= render 'form', shoe: @shoe %>
<br>
</div style="display: block;">
	<%= link_to 'Show', @shoe %> |
	<%= link_to 'Back', shoes_path %>
<div>
	

app/views/shoes/index.html.erb
<div class="mdl-cell mdl-cell--12-col">
  <p id="notice"><%= notice %></p>

  <h3><%= I18n.t('activerecord.models.shoe') %></h3>

  <%= link_to new_shoe_path, class: 'fab-action' do %>
    <button class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored">
      <i class="material-icons">add</i>
    </button>
  <% end %>

  <% I18n.with_options(scope: 'activerecord.attributes.shoe') do |i18n| %>
    <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp full-width">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric"><%= i18n.t :model %></th>
          <th class="mdl-data-table__cell--non-numeric"><%= i18n.t :brand %></th>
          <th class="mdl-data-table__cell--non-numeric">Isbn</th>
          <th class="mdl-data-table__cell--non-numeric"><%= i18n.t :release_year %></th>
          <th class="mdl-data-table__cell--non-numeric">SKU</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @shoes.each do |shoe| %>
          <tr>
            <td class="mdl-data-table__cell--non-numeric"><%= shoe.model %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= shoe.brand.name %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= shoe.isbn %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= shoe.release_year %></td>
            <td class="mdl-data-table__cell--non-numeric"><%= shoe.sku %></td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= link_to content_tag('i','visibility', class: 'material-icons'), shoe %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= link_to content_tag('i','edit', class: 'material-icons'), edit_shoe_path(shoe) %>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              <%= link_to content_tag('i','delete', class: 'material-icons'), shoe, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <br>
</div>

<%= form_tag shoes_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

app/views/shoes/new.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--2-col">
    <h5><%= "#{I18n.t('helpers.form.create')} #{I18n.t('activerecord.models.shoe')}" %></h5>
    <%= render 'form', shoe: @shoe %>    
  </div>    
</div>
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col">
    <%= link_to 'Back', shoes_path %>
  </div>    
</div>

app/views/shoes/show.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--6-col">
    <div class="mdl-card mdl-shadow--2dp">
      <div class="mdl-card__title">
        <h6 class="mdl-card__title-text">Shoe Details</h6>
      </div>
      <div class="mdl-card__supporting-text">
        <%= attribute_shoe 'M', :model, @shoe.model %><br>
        <%= attribute_shoe 'B', :brand, @shoe.brand.name %><br>
        <%= attribute_shoe 'I', :isbn, @shoe.isbn %><br>
        <%= attribute_shoe 'Y', :release_year, @shoe.release_year %><br>
        <%= attribute_shoe 'S', :sku, @shoe.sku %><br>
        <br><br>
        <div class="shoes__show_photo"><!-- Ugly but faster -->
          <%= image_tag(@shoe.photo_url.to_s, size: "200x200") %>  
          <p class="shoes__photo_description"> <%= "#{@shoe.brand.name} - #{@shoe.model}" %></p>          
        </div>
      </div>
    </div>  
    <br>
    <%= link_to 'Edit', edit_shoe_path(@shoe) %> | <%= link_to 'Back', shoes_path %>
  </div>    
</div>